version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: tu_usuario
      POSTGRES_PASSWORD: tu_contraseña
      POSTGRES_DB: mi_base_de_datos
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tu_usuario -d mi_base_de_datos"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    volumes:
      - .:/app
      - /app/bin
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: air

volumes:
  db_data:
